# Generated by Django 5.2 on 2025-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrera', models.PositiveIntegerField()),
                ('id_concepto', models.PositiveIntegerField()),
                ('modificacion', models.DateTimeField(auto_now_add=True)),
                ('importe', models.IntegerField(max_length=100)),
            ],
        ),
    ]
