# Generated by Django 5.2.7 on 2025-10-09 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0002_alter_carreracursada_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('modificacion', models.DateTimeField(auto_now_add=True)),
                ('importe', models.IntegerField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
                ('id_concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valores.concepto')),
            ],
        ),
    ]
