# Generated by Django 6.0.2 on 2026-03-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Concepto de Valor',
                'verbose_name_plural': 'Conceptos de Valor',
                'db_table': 'valores_concepto',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='carreras.carrera')),
                ('id_concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='valores.concepto')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'db_table': 'valores_valor',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
