# Generated by Django 5.2 on 2025-09-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor',
            name='importe',
            field=models.IntegerField(),
        ),
    ]
