# Generated by Django 5.2.6 on 2025-11-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valor',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
