# Generated by Django 5.2.6 on 2025-10-02 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
        ('valores', '0003_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='valor',
            name='id',
        ),
        migrations.AddField(
            model_name='concepto',
            name='id_concepto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='valor',
            name='id_valor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valor',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera'),
        ),
        migrations.AlterField(
            model_name='valor',
            name='id_concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valores.concepto'),
        ),
    ]
