# Generated by Django 5.2.7 on 2025-11-18 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('legajo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('prefijo', models.IntegerField()),
                ('telefono', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_inscripcion', models.DateTimeField(blank=True, null=True)),
                ('anio_ingreso', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
