# Generated by Django 6.0.2 on 2026-03-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('legajo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField(unique=True)),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('piso', models.CharField(blank=True, max_length=5, null=True)),
                ('departamento', models.CharField(blank=True, max_length=10, null=True)),
                ('prefijo', models.IntegerField()),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ciudad', models.ForeignKey(db_column='ciudad', on_delete=django.db.models.deletion.PROTECT, to='geografia.localidad')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos_alumno',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
