# Generated by Django 5.2 on 2025-09-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField(default='0000000000')),
                ('telefono_respaldo', models.PositiveIntegerField(default='0000000000')),
                ('inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
