# Generated by Django 5.2.6 on 2025-09-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_respaldo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
