# Generated by Django 5.2.6 on 2025-11-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='telefono_respaldo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='prefijo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
