# Generated by Django 5.1.7 on 2025-09-23 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='inscripcion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='telefono_respaldo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='anio_ingreso',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='alumno',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
