# Generated by Django 5.2.8 on 2025-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_anio_ingreso_alter_alumno_apellido_and_more'),
    ]

    operations = [

    ]
