# Generated by Django 5.2.8 on 2025-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_numero_alumno_prefijo'),
    ]

