# Generated by Django 5.2.8 on 2025-11-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_numero_alumno_prefijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='prefijo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
