# Generated by Django 5.2.7 on 2025-10-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('tipo_envio', models.CharField(choices=[('correo', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destino_deudores', models.CharField(blank=True, max_length=100, null=True)),
                ('destino_carrera', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mensajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
