# Generated by Django 5.2.7 on 2025-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('tipo_envio', models.CharField(choices=[('correo', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('en_programado', models.BooleanField(default=False)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('destino_deudores', models.JSONField(blank=True, default=list)),
                ('destino_carrera', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mensajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
