# Generated by Django 5.2.7 on 2025-11-10 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='destino_carrera',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destino_deudores',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatarios_carreras',
            field=models.ManyToManyField(blank=True, related_name='mensajes_carreras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatarios_deudores',
            field=models.ManyToManyField(blank=True, related_name='mensajes_deudores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='en_programado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
    ]
