# Generated by Django 5.2.7 on 2025-11-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_remove_mensaje_destino_carrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatarios_carreras',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatarios_deudores',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destino_carrera',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destino_deudores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
