<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-13 09:07
=======
# Generated by Django 5.2.8 on 2025-11-13 13:24
>>>>>>> 4dcba221

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarreraCursada',
            fields=[
                ('pk', models.CompositePrimaryKey('alumno', 'carrera', blank=True, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_cursadas', to='alumnos.alumno')),
                ('carrera', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
                ('id_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.estado')),
            ],
            options={
                'db_table': 'carreras_cursadas',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.estado'),
        ),
    ]
