# Generated by Django 5.1.7 on 2025-09-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarreraCursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.estado')),
            ],
            options={
                'unique_together': {('id_alumno', 'id_carrera')},
            },
        ),
    ]
