# Generated by Django 6.0.2 on 2026-03-09 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'carreras_estado',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1E3A8A', max_length=7)),
                ('id_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='carreras.estado')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carreras_carrera',
            },
        ),
        migrations.CreateModel(
            name='CarreraCursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_inscripcion', models.DateTimeField(blank=True, null=True)),
                ('anio_ingreso', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('alumno', models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.CASCADE, related_name='carreras_cursadas', to='alumnos.alumno')),
                ('carrera', models.ForeignKey(db_column='carrera_id', on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_cursando', to='carreras.carrera')),
                ('id_estado', models.ForeignKey(db_column='id_estado_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carreras_cursadas', to='carreras.estado')),
            ],
            options={
                'verbose_name': 'Carrera cursada',
                'verbose_name_plural': 'Carreras cursadas',
                'db_table': 'carreras_cursadas',
                'unique_together': {('alumno', 'carrera')},
            },
        ),
    ]
