# Generated by Django 5.2.6 on 2025-10-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreracursada',
            name='pk',
            field=models.CompositePrimaryKey('alumno', 'carrera', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
