# Generated by Django 5.2.8 on 2025-11-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='carreracursada',
            options={'managed': False, 'verbose_name': 'Cursada', 'verbose_name_plural': 'Cursadas'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='id_estado',
        ),
        migrations.AlterModelTable(
            name='carrera',
            table='carreras_carrera',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='carreras_estado',
        ),
    ]
