# Generated by Django 5.2.6 on 2025-09-25 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreracursada',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera'),
        ),
        migrations.AlterField(
            model_name='carreracursada',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.estado'),
        ),
    ]
