# Generated by Django 5.2.6 on 2025-12-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_alter_carrera_options_alter_carreracursada_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.estado'),
        ),
    ]
