# Generated by Django 5.2.6 on 2025-11-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_telefono_respaldo_alumno_numero_and_more'),
        ('carreras', '0002_alter_carreracursada_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreracursada',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_cursadas', to='alumnos.alumno'),
        ),
    ]
