# Generated by Django 5.2.6 on 2025-11-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_alter_carreracursada_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.estado'),
        ),
    ]
