# Generated by Django 6.0.2 on 2026-02-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0005_cargar_estados_faltantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='color',
            field=models.CharField(default='#1E3A8A', max_length=7),
        ),
    ]
