<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-25 03:23
=======
# Generated by Django 5.2.7 on 2025-11-25 21:41
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
<<<<<<< HEAD
=======
        ('valores', '0001_initial'),
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f
    ]

    operations = [
        migrations.CreateModel(
            name='MesPago',
            fields=[
                ('id_mes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Mes de Pago',
                'verbose_name_plural': 'Meses de Pago',
<<<<<<< HEAD
                'db_table': 'ctacte_mespago',
=======
                'db_table': 'mes_pago',
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
<<<<<<< HEAD
                'db_table': 'ctacte_metodopago',
=======
                'db_table': 'metodo_pago',
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('importe_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
<<<<<<< HEAD
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='alumnos.alumno')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='ctacte.metodopago')),
=======
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alumnos.alumno')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ctacte.metodopago')),
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
<<<<<<< HEAD
                'db_table': 'ctacte_pago',
=======
                'db_table': 'pago',
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_detalle', to='ctacte.mespago')),
=======
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('anio_pago', models.PositiveIntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='valores.concepto')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_detalle', to='ctacte.mespago')),
>>>>>>> 62599f47832da27fc8dd1e1c65c40bf41d49295f
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ctacte.pago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'db_table': 'pago_detalle',
                'unique_together': {('pago', 'mes')},
            },
        ),
    ]
