<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-13 09:07
=======
# Generated by Django 5.2.8 on 2025-11-13 13:25
>>>>>>> 4dcba221

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
<<<<<<< HEAD
=======
        ('valores', '0001_initial'),
>>>>>>> 4dcba221
    ]

    operations = [
        migrations.CreateModel(
            name='MesPago',
            fields=[
                ('id_mes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
<<<<<<< HEAD
=======
            options={
                'db_table': 'mes_pago',
            },
>>>>>>> 4dcba221
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
=======
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'metodo_pago',
            },
>>>>>>> 4dcba221
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('fecha_pago', models.DateTimeField()),
=======
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
>>>>>>> 4dcba221
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctacte.metodopago')),
            ],
<<<<<<< HEAD
=======
            options={
                'db_table': 'pago',
            },
>>>>>>> 4dcba221
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
<<<<<<< HEAD
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pk', models.CompositePrimaryKey('pago', 'mes', blank=True, editable=False, primary_key=True, serialize=False)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctacte.mespago')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctacte.pago')),
=======
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anio_pago', models.PositiveIntegerField()),
                ('id_concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='valores.concepto')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctacte.mespago')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ctacte.pago')),
>>>>>>> 4dcba221
            ],
            options={
                'db_table': 'pago_detalle',
            },
        ),
    ]
