# Generated by Django 5.1.7 on 2025-09-24 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alter_alumno_options_remove_alumno_fecha_nacimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesPago',
            fields=[
                ('id_mes', models.AutoField(db_column='id_mes', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'mes_pago',
                'ordering': ['id_mes'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='id_metodo_pago', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'metodos_pagos',
                'ordering': ['id_metodo_pago'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='id_pago', primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('importe_total', models.DecimalField(db_column='importe_total', decimal_places=2, max_digits=12)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alumnos.alumno')),
                ('metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='ctacte.metodopago')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_pago', '-id_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id_detalle', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes', models.ForeignKey(db_column='id_mes', on_delete=django.db.models.deletion.PROTECT, to='ctacte.mespago')),
                ('pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ctacte.pago')),
            ],
            options={
                'db_table': 'pago_detalle',
                'constraints': [models.UniqueConstraint(fields=('pago', 'mes'), name='uq_pago_mes')],
            },
        ),
    ]
