# Generated by Django 5.2.7 on 2025-10-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('ctacte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mespago',
            options={'verbose_name': 'Mes de Pago', 'verbose_name_plural': 'Meses de Pago'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='pagodetalle',
            options={'verbose_name': 'Detalle de Pago', 'verbose_name_plural': 'Detalles de Pago'},
        ),
        migrations.AlterUniqueTogether(
            name='pagodetalle',
            unique_together={('pago', 'mes')},
        ),
        migrations.AddField(
            model_name='pagodetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ctacte.metodopago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagodetalle',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagodetalle',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_detalle', to='ctacte.mespago'),
        ),
        migrations.AlterField(
            model_name='pagodetalle',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ctacte.pago'),
        ),
        migrations.AlterModelTable(
            name='mespago',
            table='ctacte_mespago',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='ctacte_metodopago',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='ctacte_pago',
        ),
        migrations.RemoveField(
            model_name='pagodetalle',
            name='pk',
        ),
    ]
