# Generated by Django 5.2.8 on 2025-11-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctacte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagodetalle',
            old_name='id_detalle',
            new_name='id',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pago',
        ),
    ]
