# Generated by Django 5.2.6 on 2025-10-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctacte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='metodo_pago',
            new_name='id_metodo_pago',
        ),
    ]
