# Generated by Django 5.2.6 on 2025-10-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctacte', '0002_rename_metodo_pago_pago_id_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
