# Generated by Django 5.2.8 on 2025-11-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctacte', '0002_rename_id_detalle_pagodetalle_id_alter_pago_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagodetalle',
            old_name='id',
            new_name='id_detalle',
        ),
    ]
