# Generated by Django 5.2.8 on 2025-11-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctacte', '0003_rename_id_pagodetalle_id_detalle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pago',
            table='ctacte_pago',
        ),
    ]
