# Generated by Django 5.2.6 on 2025-10-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctacte', '0003_rename_usuario_pago_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_usuario',
        ),
    ]
