# Generated by Django 5.2.7 on 2025-10-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mensaje',
            table='mensajes',
        ),
    ]
