# Generated by Django 5.2.6 on 2025-11-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuario',
        ),
    ]
